version: "3.9"

services:

  # ==================
  # docker dind
  # ==================

  dind:
    container_name: docker-dind
    privileged: true
    image: docker:dind
    ports:
      - 2376:2376
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      default:
        aliases:
          - docker

  # ==================
  # jenkins (blueocean)
  # ==================

  jenkins:
    container_name: jenkins-blueocean
    image: jenkinsci/blueocean
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1

volumes:
  jenkins-docker-certs:
  jenkins-data: